### ISSUE TITLE
Paper wallet account balance 

### ISSUE THREAD

**Issue by kochj79** [BTA-BATA/BATA-SOURCE#44]
Hello,

How can i get to the BATA coin paper wallet so I can transfer BATA coins and see my BATA coin account balance? Ive downloaded the wallet on github and made an offline paper wallet, sent coins to its public address but dont know how to get acces to the wallet. Please help.

Regards JK

**Comment by midnight-miner** [comment]
Does the balance show in the Block Explorer for the address you created?
In order to 'spend' the coins you must import the 'private key' that was generated when you created the 
paper wallet.
If you help 'help' in the console window in the Bata wallet you will see the command to import private keys and the instruction on how to complete.

**Comment by kochj79** [comment]
I only have the paper wallet and know nothing about a block explorer, how
does this work?
Can you give me a link please?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-08-12 0:40 GMT+02:00 MidnightMiner <notifications@github.com>:

**Comment by kochj79** [comment]
Or do you mean the bata core wallet? Should I use that in order to get
access to the paper wallet!? Because the paper wallet has no "help"
section.



2017-08-12 8:45 GMT+02:00 J K <kochj79@gmail.com>:

**Comment by BTA-BATA** [comment]
A blockexplorer is: https://chainz.cryptoid.info/bta/ 
Go to the page and enter your address from the wallet.

**Comment by BTA-BATA** [comment]
Please create an account https://bata-blockchain.signup.team/ if you require further assistance.

**Comment by kochj79** [comment]
Thank you for your quick reply I can see it now ;-D

Regards Jeroen

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-08-12 9:16 GMT+02:00 pc888 <notifications@github.com>:

**Comment by BTA-BATA** [comment]
Good to hear. Any issues or questions let us know.

**Comment by kochj79** [comment]
Hello,

when I click the send button below the QR code, nothing happens. How can I
send Bata?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-08-12 15:06 GMT+02:00 pc888 <notifications@github.com>:

**Comment by BTA-BATA** [comment]
Please join the slack address provided as this is not a support channel.

**Comment by kochj79** [comment]
Hello,

Sorry to contact you again but Ive asked for help on multiple websites,
also joined bata slack but nobody replies to my question.
When I go to the block explorer I can see my account balance, but when I
click on SEND nothing happens.

Regards Jeroen

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-08-12 17:24 GMT+02:00 pc888 <notifications@github.com>:

**Comment by BTA-BATA** [comment]
Hello Jeroen you can only send BTA via your wallet or via exchange, not the blockchain explorer. If you have a paper wallet you will download wallet off website then as per instructions in earlier response from midnight-miner:  
In order to 'spend' the coins you must import the 'private key' that was generated when you created the
paper wallet.
If you click 'help' in the console window in the Bata wallet you will see the command to import private keys and the instruction on how to complete.
Regards,
Peter

**Comment by kochj79** [comment]
Hello,

thanks for your respond. In the folder on my computer I click on the
"index.html" and then get to see the paper wallet generator. This is where
I created the public address and got the private key. But there is no
"help" section on this page. What do I do wrong, am i on the wrdng page and
how do i get to the right one?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-08-14 15:47 GMT+02:00 pc888 <notifications@github.com>:

**Comment by kochj79** [comment]
Can you please tell me how to get to the the wallet. I only have accessed
the wallet generator and the block explorer but they're no wallets.

2017-08-14 17:17 GMT+02:00 J K <kochj79@gmail.com>:

**Comment by BTA-BATA** [comment]
Download Wallet : https://bata.io/wallets  then use instructions previously provided.

**Comment by kochj79** [comment]
I did al that my friend, I downloaded the paper wallet, installed it
offline, printed the paper, went to block explorer to see the account
balance, clicked on the SEND BATA button there.....but it doesnt work! When
you install the offline wallet you will see there IS NO help section and no
instructions there. I am a noob but not that noobish okey. I just cant
figure it out! Would you please help me out here?



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-08-15 7:53 GMT+02:00 pc888 <notifications@github.com>:

**Comment by BTA-BATA** [comment]
Paper Wallet is for Long term or offline storage. The only way to spend or send your BTA is with a Bata Core Wallet (QT).
The block explorer only shows your balance. The send Bata button you are trying to press is for donations to that address.
If you want to send BTA please download the Windows wallet (QT) so that you can import your private key that was generated when you created the paper wallet.
If you click 'help' in the console window in the (QT) Bata wallet you will see the command to import private keys and the instruction on how to complete.
