### ISSUE TITLE
fake first block

### ISSUE THREAD

**Issue by alexeyneu** [BTA-BATA/BATA-SOURCE#67]
so you have :  
`486604799` goes as nbits to scriptSig that goes to hashMerkleRoot  
meanwhile    
`0x1e0ffff0`  goes to blockheader directly.

https://github.com/BTA-BATA/BATA-SOURCE/blob/0b59eed76a7442b4ec440d90eec411677b1e3f8a/src/chainparams.cpp#L142  
  
https://github.com/BTA-BATA/BATA-SOURCE/blob/0b59eed76a7442b4ec440d90eec411677b1e3f8a/src/chainparams.cpp#L150  
really nobody knows what means nbits in this bitcoin scripsig

**Comment by midnight-miner** [comment]
This appears to be an oversight on the update from core 0.8.7 to core 0.10.
I will fix this up on the next revision so that the Genesis block resolves properly.

You can see where the error occured from the same source in LiteCoin that was used as the reference code for the Core 0.10 update:

[https://github.com/litecoin-project/litecoin/blob/0.10/src/chainparams.cpp#L152](url)
